"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import BootstrapActivation from "@/helpers/BootstrapActivation";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import {useState} from "react";
import {IAccountInfo, AccountContext} from "@/context/AccountContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [accountInfo, setAccountInfo] = useState<IAccountInfo | undefined>();

    const updateAccountInfo = (value: IAccountInfo) => {
        setAccountInfo(value);
        localStorage.setItem("_jwt", value.jwt!);
        localStorage.setItem("_refreshToken", value.refreshToken!);

    }
  return (
    <html lang="en">
      <body>
      <AccountContext.Provider value={{
          accountInfo: accountInfo,
          setAccountInfo: updateAccountInfo,
      }}>

      <Header/>
      <div className="container">
          <main>
            {children}
            <BootstrapActivation/>
          </main>
      </div>
      <Footer/>
          </AccountContext.Provider>
      </body>
    </html>
  );
}
